server:
  port: 17773
spring:
  application:
    name: hey-eureka-client
eureka:
  client:
    #注册到eureka注册中心
    register-with-eureka: true
    #获取注册实例列表
    fetch-registry: true
    #配置注册中心地址
    service-url:
      #配置注册到有登录认证的注册中心 地址格式:http://${username}:${password}@${hostname}:${port}/eureka/
      defaultZone: http://wsork:admin@localhost:17767/eureka/

