server:
  port: 17771
spring:
  application:
    name: hey-eureka-client
  profiles:
    # 环境配置
    active: replica
eureka:
  client:
    #注册到eureka注册中心
    register-with-eureka: true
    #获取注册实例列表
    fetch-registry: true
    #配置注册中心地址
    service-url:
      #配置注册中心地址
      defaultZone: http://localhost:17770/eureka/

