server:
  port: 17767
spring:
  application:
    name: hey-eureka-security
  security:
    user:
      name: wsork
      password: admin
eureka:
  instance:
    #指定主机地址
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
