server:
  port: 17768
spring:
  application:
    name: hey-eureka-server
eureka:
  instance:
    #指定主机地址
    hostname: replica2
  client:
    #指定是否要从注册中心获取服务
    fetch-registry: true
    #指定是否要注册到注册中心
    register-with-eureka: true
    service-url:
      #注册到另一个Eureka注册中心
      defaultZone: http://replica2:17769/eureka/